# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
