version: "3"

services:
  files:
    image: docker.clsi.ca/sgm/mxlive-dataproxy:latest
    environment:
      - SERVER_NAME=files
      - CERT_PATH=/etc/ssl/proxy
      - COMMON_NAME=files
    networks:
      - sgmxlive_network
    volumes:
      - ./apache_config/:/etc/httpd/conf.d/:ro
      - ../../mxlive-dataproxy/local:/dataserver/local
      - ../../mxlive-dataproxy/local/users:/users:ro
      - /beamlinedata:/beamlinedata:ro
      - ../../mxlive-dataproxy/local/logs:/logs
      - ../../mxlive-dataproxy/local/cache:/cache
      - sgmcerts:/etc/ssl/proxy
    ports:
      - "8080:443"
    deploy:
      restart_policy:
        delay: 15s
        window: 60s

networks:
   sgmxlive_network:
     external: true

volumes:
  sgmcerts:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/home/arthurz/sgmlive/certs'
  media:
  pdf: